#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Guida.Droid.Resource", IsApplication=true)]

namespace Guida.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int lung = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int antibioticInfoText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int antibioticNameText = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int antibioticSearchButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int antibiticTitleText = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int antibitoicSearchField = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int authStatusText = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int bodyButton = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int imageButton1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageButton2 = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int listView1 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int loginButton = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int passwordField = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int patientInfoButton = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int searchAntibioticButton = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int usernameField = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AntibioticInformation = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AntibioticSearch = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BodyParts = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListP = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PInfo = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int login = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
